[package]
name = "egui-ansi"
version = "0.1.0"
edition = "2024"

[dependencies]
ansi = { git = "https://github.com/ParkerTenBroeck/ansi.git" }
egui = "*"
unicode-width = "*"

[dev-dependencies]
eframe = "*"